#+title: text.org
#+startup: indent


* 1. The periodic table displays the elements in increasing atomic number and shows how periodicity of the physical and chemical properties of the elements relates to atomic structure. As a basis for understanding this concept: 
a.  how to relate the position of an element in the periodic table to its atomic number and atomic mass. 
b.  how to use the periodic table to identify metals, semimetals, nonmetals, and halogens. 
c.  how to use the periodic table to identify alkali metals, alkaline earth metals and transition metals, trends in ionization energy, electronegativity, and the relative sizes of ions and atoms. 
d.  how to use the periodic table to determine the number of electrons available for bonding. 
e.  the nucleus of the atom is much smaller than the atom yet contains most of its mass. 
f.  how to use the periodic table to identify the lanthanide, actinide, and transactinide elements and know that the transuranium elements were synthesized and identified in laboratory experiments through the use of nuclear accelerators. 
g.  how to relate the position of an element in the periodic table to its quantum electron configuration and to its reactivity with other elements in the table. 
h.  the experimental basis for Thomson’s discovery of the electron, Rutherford’s nuclear atom, Millikan’s oil drop experiment, and Einstein’s explanation of the photoelectric effect. 
i.  the experimental basis for the development of the quantum theory of atomic structure and the historical importance of the Bohr model of the atom. 
j.  that spectral lines are the result of transitions of electrons between energy levels and that these lines correspond to photons with a frequency related to the energy spacing between levels by using Planck’s relationship (E = hv). 

 
 
* 2. Biological, chemical, and physical properties of matter result from the ability of atoms to form bonds from electrostatic forces between electrons and protons and between atoms and molecules. As a basis for understanding this concept: 
a.  atoms combine to form molecules by sharing electrons to form covalent or metallic bonds or by exchanging electrons to form ionic bonds. 
b.  chemical bonds between atoms in molecules such as H2, CH4, NH3, H2CCH2, N2, Cl2, and many large biological molecules are covalent. 
c.  salt crystals, such as NaCl, are repeating patterns of positive and negative ions held together by electrostatic attraction. 
d.  the atoms and molecules in liquids move in a random pattern relative to one another because the intermolecular forces are too weak to hold the atoms or molecules in a solid form. 
e.  how to draw Lewis dot structures. 
f.  how to predict the shape of simple molecules and their polarity from Lewis dot structures. 
g.  how electronegativity and ionization energy relate to bond formation. 
h.  how to identify solids and liquids held together by Van der Waals forces or hydrogen bonding and relate these forces to volatility and boiling/ melting point temperatures. 


* 3. The conservation of atoms in chemical reactions leads to the principle of conservation of matter and the ability to calculate the mass of products and reactants. As a basis for understanding this concept: 
a.  how to describe chemical reactions by writing balanced equations. 
b.  the quantity one mole is set by defining one mole of carbon 12 atoms to have a mass of exactly 12 grams. 
c.  one mole equals 6.02 X 1023 particles (atoms or molecules). 
d.  how to determine the molar mass of a molecule from its chemical formula and a table of atomic masses and how to convert the mass of a molecular substance to moles, number of particles, or volume of gas at standard temperature and pressure. 
e.  how to calculate the masses of reactants and products in a chemical reaction from the mass of one of the reactants or products and the relevant atomic masses. 
f.  how to calculate percent yield in a chemical reaction. 
g.  how to identify reactions that involve oxidation and reduction and how to balance oxidation-reduction reactions. 


* 4. The kinetic molecular theory describes the motion of atoms and molecules and explains the properties of gases. As a basis for understanding this concept: 
a.  the random motion of molecules and their collisions with a surface create the observable pressure on that surface. 
b.  the random motion of molecules explains the diffusion of gases. 
c.  how to apply the gas laws to relations between the pressure, temperature, and volume of any amount of an ideal gas or any mixture of ideal gases. 
d.  the values and meanings of standard temperature and pressure (STP). 
e.  how to convert between the Celsius and Kelvin temperature scales. 
f.  there is no temperature lower than 0 Kelvin. 
g.  the kinetic theory of gases relates the absolute temperature of a gas to the average kinetic energy of its molecules or atoms. 
h.  how to solve problems by using the ideal gas law in the form PV = nRT.   
i.  how to apply Dalton’s law of partial pressures to describe the composition of gases and Graham’s law to predict diffusion of gases. 


* 5. Acids, bases, and salts are three classes of compounds that form ions in water solutions. As a basis for understanding this concept: 
a. the observable properties of acids, bases, and salt solutions. 
b.  acids are hydrogen-ion-donating and bases are hydrogen-ion accepting substances. 
c.  strong acids and bases fully dissociate and weak acids and bases partially dissociate. 
d.  how to use the pH scale to characterize acid and base solutions. 
e.  the Arrhenius, Brønsted-Lowry, and Lewis acid–base definitions. 
f.  how to calculate pH from the hydrogen-ion concentration. 
g.  buffers stabilize pH in acid–base reactions. 


* 6. Solutions are homogenous mixtures of two or more substances. As a basis for understanding this concept: 
a.  the definitions of solute and solvent. 
b.  how to describe the dissolving process at the molecular level by using the concept of random molecular motion. 
c.  temperature, pressure, and surface area affect the dissolving process. 
d.  how to calculate the concentration of a solute in terms of grams per liter, molarity, parts per million, and percent composition. 
e.  the relationship between the molality of a solute in a solution and the solution’s depressed freezing point or elevated boiling point. 
f.  how molecules in a solution are separated or purified by the methods of chromatography and distillation. 


* 7. Energy is exchanged or transformed in all chemical reactions and physical changes of matter. As a basis for understanding this concept: 
a.  how to describe temperature and heat flow in terms of the motion of molecules (or atoms). 
b.  chemical processes can either release (exothermic) or absorb (endothermic) thermal energy. 
c.  energy is released when a material condenses or freezes and is absorbed when a material evaporates or melts. 
d.  how to solve problems involving heat flow and temperature changes, using known values of specific heat and latent heat of phase change. 
e.  how to apply Hess’s law to calculate enthalpy change in a reaction. 
f.  how to use the Gibbs free energy equation to determine whether a reaction would be spontaneous. 


* 8. Chemical reaction rates depend on factors that influence the frequency of collision of reactant molecules. As a basis for understanding this concept: 
a.  the rate of reaction is the decrease in concentration of reactants or the increase in concentration of products with time. 
b.  how reaction rates depend on such factors as concentration, temperature, and pressure. 
c.  the role a catalyst plays in increasing the reaction rate. 
d.  *the definition and role of activation energy in a chemical reaction. 

* 9. Chemical equilibrium is a dynamic process at the molecular level. As a basis for understanding this concept: 
a.  how to use LeChatelier’s principle to predict the effect of changes in concentration, temperature, and pressure. 
b.  equilibrium is established when forward and reverse reaction rates are equal. 
c.  how to write and calculate an equilibrium constant expression for a reaction. 
 

* 10. The bonding characteristics of carbon allow the formation of many different organic molecules of varied sizes, shapes, and chemical properties and provide the biochemical basis of life. As a basis for understanding this concept: 
a.  large molecules (polymers), such as proteins, nucleic acids, and starch, are formed by repetitive combinations of simple subunits. 
b.  the bonding characteristics of carbon that result in the formation of a large variety of structures ranging from simple hydrocarbons to complex polymers and biological molecules. 
c.  amino acids are the building blocks of proteins. 
d.  the system for naming the ten simplest linear hydrocarbons and isomers that contain single bonds, simple hydrocarbons with double and triple bonds, and simple molecules that contain a benzene ring. 
e.  how to identify the functional groups that form the basis of alcohols, ketones, ethers, amines, esters, aldehydes, and organic acids. 
f.  the R-group structure of amino acids and know how they combine to form the polypeptide backbone structure of proteins. 


* 11. Nuclear processes are those in which an atomic nucleus changes, including radioactive decay of naturally occurring and human-made isotopes, nuclear fission, and nuclear fusion. As a basis for understanding this concept: 
a.  protons and neutrons in the nucleus are held together by nuclear forces that overcome the electromagnetic repulsion between the protons. 
b.  the energy release per gram of material is much larger in nuclear fusion or fission reactions than in chemical reactions. The change in mass (calculated by E = mc^2 ) is small but significant in nuclear reactions. 
c.  some naturally occurring isotopes of elements are radioactive, as are isotopes formed in nuclear reactions. 
d.  the three most common forms of radioactive decay (alpha, beta, and gamma) and know how the nucleus changes in each type of decay. 
e.  alpha, beta, and gamma radiation produce different amounts and kinds of damage in matter and have different penetrations. 
f.  how to calculate the amount of a radioactive substance remaining after an integral number of half lives have passed. 
g.  protons and neutrons have substructures and consist of particles called quarks. 
