#+title: text.org

* 1 Chemistry: An Introduction 2



* 2 Matter 22

** the nature of matter

+ key terms:
  + matter
  + atoms
  + compounds
  + molecules
  + elements
  + solid
  + liquid
  + gas
    
+ Objectives
  + To learn about the composition of matter
  + To learn the difference between elements and compounds
  + To define the three states of matter


*** A. The Particulate Nature of Matter

*Matter*, the “stuff” of which the universe is composed, has two characteristics: it has mass and it occupies space. Matter comes in a great variety of forms: the stars, the air that you are breathing, the gasoline that you put in your car, the chair on which you are sitting, the turkey in the sandwich you may have eaten for lunch, the tissues in your brain that allow you to read and understand this sentence, and so on.

As we look around our world, we are impressed by the great diversity of matter. Given the many forms and types of matter, it seems difficult to believe that all matter is composed of a small number of fundamental particles. It is surprising that the fundamental building blocks in chocolate cake are very similar to the components of air.

**** The Atomic Nature of Matter
How do we know that matter is composed of the tiny particles we call atoms? After all, they are far too small to be seen with the naked eye. It turns out that after literally thousands of years of speculation, we can finally “see” the atoms that are present in matter. In recent years scientists have developed a device called a scanning tunneling microscope (STM) that, although it works
quite differently from an optical microscope, can produce images of atoms.

All matter consists of tiny particles called atoms. But when you look at objects such as nails or pennies, you don’t see these particles. Why not? The atoms are very tiny and can be seen only with a powerful magnifying instrument. You may have encountered the same concept in your life when you looked at a beach from a distance. The sand looks uniform—you can’t see the separate particles. As you get close, however, the individual grains of sand become apparent.

So, the conclusion is that although objects in the macroscopic world typically look quite continuous and uniform, they are really particulate in nature—they are made of atoms. We can “see” them with powerful electronic microscopes.

*** Elements and Compounds

We have just considered the most important idea in chemistry: matter is composed of tiny particles we call *atoms*. If all matter is made up of tiny particles called atoms, are all atoms alike? That is, is copper metal made of the same kind of atoms as gold? The answer is no. Copper atoms and gold atoms are different. Scientists have learned that all matter is composed from about 100 different types of atoms. For example, air is mostly gaseous oxygen and nitrogen. The nitrogen atoms are different from the
oxygen atoms, which in turn are different from copper atoms, which differ from gold atoms.

You can think of the matter in the universe like the words in a book. If you break all the words in this book apart into their component letters, you will end up with “large piles” of only 26 letters. The English alphabet allows you to construct thousands of words from just 26 letters. Similarly, all the matter in the universe is constructed by putting approximately 100 types of atoms together in various ways. The different types of matter are like the different words in a book. When we separate all of the universe into its atoms, we find approximately 100 different atoms. We call these 100 types of atoms the elements of the universe.

To illustrate this idea, consider the letters A, D, and M. Using these letters you can make many words, such as MAD, DAM, DAD, and MADAM (can you think of others?). Each word represents something very different. Thus, with only three letters, you can represent several unique things or ideas.

* 3 Chemical Foundations: Elements, Atoms, and Ions 48
* 4 Nomenclature 92
* 5 Measurements and Calculations 124
* 6 Chemical Composition 170
7 Chemical Reactions: An Introduction 216
8 Reactions in Aqueous Solutions 238
9 Chemical Quantities 278
10 Energy 318
11 Modern Atomic Theory 358
12 Chemical Bonding 398
13 Gases 440
14 Liquids and Solids 486
15 Solutions 518
16 Acids and Bases 560
17 Equilibrium 594
18 Oxidation–Reduction Reactions and Electrochemistry 634
19 Radioactivity and Nuclear Energy 666
20 Organic Chemistry 698
21 Biochemistry 750
