
#+title: text.org
#+startup: indent

* The periodic table displays the elements in increasing atomic number and shows how periodicity of the physical and chemical properties of the elements relates to atomic structure. As a basis for understanding this concept:


* Periodic Table

** Periodic Trends
*** atomic number
*** atomic mass
*** ionization energy
*** electronegativity
*** relative sizes of ions and atoms. 
*** number of electrons available for bonding. 

** Families of elements
*** metals
*** semimetals 
*** nonmetals 
*** halogens 
*** alkali metals 
*** alkaline earth metals
*** transition metals
*** lanthanide 
*** actinide 
*** transactinide elements  

** Experimental basis

*** Thomson's discovery of the electron, 
*** Rutherford's nuclear atom, 
*** Millikan's oil drop experiment, and 
*** Einstein's explanation of the photoelectric effect. 
*** the historical importance of the Bohr model of the atom. 

** Nuclear Physics

*** the nucleus of the atom is much smaller than the atom yet contains most of its mass. 
*** quantum electron configuration
*** quantum theory of atomic structure
*** spectral lines are the result of transitions of electrons between energy levels and 
*** that these lines correspond to photons with a frequency related to the energy spacing between levels by using Planck's relationship (E = hv). 
*** the transuranium elements were synthesized and identified in laboratory experiments through the use of nuclear accelerators. 

* Biological, chemical, and physical properties of matter result from the ability of atoms to form bonds from electrostatic forces between electrons and protons and between atoms and molecules. As a basis for understanding this concept:

** atoms combine to form molecules by sharing electrons to form covalent or metallic bonds or by exchanging electrons to form ionic bonds. 
** chemical bonds between atoms in molecules such as H_2, CH_4, NH_3, H_{2}CCH_2, N_2, Cl_2, and many large biological molecules are covalent. 
** salt crystals, such as NaCl, are repeating patterns of positive and negative ions held together by electrostatic attraction. 
** the atoms and molecules in liquids move in a random pattern relative to one another because the intermolecular forces are too weak to hold the atoms or molecules in a solid form.
** draw Lewis dot structures. 
** predict the shape of simple molecules and their polarity from Lewis dot structures. 
** electronegativity and ionization energy relate to bond formation. 
** identify solids and liquids held together by van der Waals forces or hydrogen bonding and relate these forces to volatility and boiling/ melting point temperatures.
