
* 3b2 Discussion Techniques and Student Participation

Teacher uses intentional,differentiated strategies to engage all students in discussions, attempting gradual release from teacher-directed to studentinitiated conversation.
Strategies affirm the students' culture and language. Student participate in intellectually challenging discussions.

* 3c1 Standards-Based Projects, Activities, and Assignments 

Instructional projects, activities and assignments are aligned to the instructional standards, require higher levels of thinking, are culturally and linguistically relevant1, and
may include real-world application. Most learners are cognitively engaged,constructing their own understanding, and exploring content. The learning activities are differentiated, as necessary, to incorporate the
social emotional learning of all subgroups.

* 3d3 Feedback to Students 

Teacher's feedback to learners is timely, frequent, relevant, accurate, aligned to the instructional outcome and is sensitive to students' culture and language, Specific feedback guides learners to revise and improve their work, fostering self-efficacy and a growth mindset.

* 1a2 Knowledge of Content-Related Pedagogy

Teacher's plan reflects intentional
selection of effective researchbased pedagogical approaches
in the discipline, including cultural
or linguistic responsiveness1 or
social emotional wellness2, and
are appropriate for the essential
understandings and big ideas
addressed in the lesson. Teacher
plans appropriate use of
technology and of 21st Century
Skills. Teacher anticipates
students' misunderstandings.

* 2a3 Academic Climate

Students demonstrate a
growth mindset and freely
share their culture, language,
ideas, or opinions, and take
risks in learning. Student
mistakes are treated as
learning opportunities by the
teacher.

* 3a1 Communicating the Purpose of the Lesson

Teacher's explanation of the instructional purpose is clear to students, including connections to prior
knowledge, culture, language or big ideas and essential understandings. Most students understand and are able to
communicate the purpose of the lesson to their peers and others. 