#+title: week one: knowing your learners

The Next Generation Science Standards (NGSS) are the de dicto guidlines for science instruction in California.  Los Angeles Unified School District(LAUSD), the district I anticipate working as a science educator, has adopted the thee-course model for high school science education(citation). This means that sudents take Biology, Chemistry and Physics in that order. I have decided to plan a week long lesson in atomic theory. This has tradtionally been an early unit covered in high school chemistry. 

* Prior academic knowledge 

- assessment: Students will take a pre-assessment link to determine knowledge of subject matter to be covered in the atomic theory lesson.
- data collection: Student performance on the pre-assessment will inform instruction for the comming week. The goal is to develop a real-time data collection system using web-based technology.
 

* Cultural and linguistic resources and funds of knowledge

- assessment: I would assess cultural and linguqistic resources in a two part collaborative assignment. Students will form small groups and discuss food preparation is in their family. The second part of the assignment would be a discussion related to the chemistry of food.
- data collection: This will be an opportunity to build a sense of community in the classroom and an opportunity for me to build stronger relationships with my students.  

* Prior experience and interests and life experience(s) that may require additional academic and/or emotional support

- assessment: Students will complete a survey that will assess prior interest in Chemistry and a student information form.
- data collection: Keeping track of up to 150 students can be challenging. My plan is to utilize a database application that will allow for quick retrieval of student information. This will, hopefully, allow faster and more efficient incorporation of student data in instruction planning.

* Social identity (students’ expressed self-concept derived from a social group that is evident through peer and/or adult interactions inside or outside of school)



* Developmental considerations
