#+title: week one: knowing your learners
#+author: Tyler Maxwell


The Next Generation Science Standards (NGSS) are the guidelines for science instruction in California.  Los Angeles Unified School District(LAUSD), the district I anticipate working as a science educator, has adopted the “thee-course” model for high school science education(citation). This means that students take Biology, Chemistry and Physics in that order. I have decided to plan a week-long lesson in atomic theory. This has traditionally been an early unit covered in high school chemistry. 

In efforts to differentiate instruction and make class materials available to all students, I have created a website for the class. 


* Prior academic knowledge 

- assessment: Students will take a pre-assessment  to determine knowledge of subject matter to be covered in the atomic theory lesson.
- data collection: Student performance on the pre-assessment will inform instruction for the coming week. The goal is to develop a real-time data collection system using web-based technology.
 

* Cultural and linguistic resources and funds of knowledge

- assessment: I would assess cultural and linguistic resources in a two part collaborative assignment. Students will form small groups and discuss food preparation in their family. The second part of the assignment would be a discussion related to the chemistry of food. 
- data collection: This will be an opportunity to build a sense of community in the classroom and an opportunity for me to build stronger relationships with my students.  

* Prior experience and interests and life experience(s) that may require additional academic and/or emotional support

- assessment: Students will complete a survey that will assess prior interest in Chemistry and a student information form.
- data collection: Keeping track of up to 150 students can be challenging. My plan is to utilize a database application that will allow for quick retrieval of student information. This will, hopefully, allow faster and more efficient incorporation of student data in instruction planning.

* Developmental considerations

All instructional planning is subject to change and modification. Through careful reflection and observation, the assessments and activities presented here will be in a constant state of development. I am not teaching Chemistry at this point. I am working as a substitute teacher in LAUSD. I was a social studies teacher for about seven years. I have been out the classroom for about 15 years. I see this transition as a chance to learn from my previous experience and enhance and refresh my skills. I am embarrassed to say I did not implement many of the strategies found in this assignment when I was in the classroom. I truly believe that this level of reflection and investigation would have made me a much more effective teacher.

In completing this assignment, I have conducted research and found several resources for science, and specifically Chemistry, education in LAUSD. I am grateful for the level and depth of insight provided by this assignment.
