#+title: Chemistry AB Course Syllabus
#+author: Mr. Maxwell
#+startup: indent
#+latex_header:\usepackage{geometry}
#+latex_header:\geometry{margin=2cm}

* Course Information
#+ATTR_LaTeX: :center nil
| *course:*       | Chemistry AB |
| *prerequisite:* | Algebra 1 AB |
| *corequisite:*  | Geometry AB  |

* Instructor Information
#+ATTR_LaTeX: :center nil
| *name:*         | Mr. Maxwell             |
| *email:*        | tyler.maxwell@lausd.net |
| *room:*         | 305E                    |
| *office hours:* | By appointment          |

* Course Description
Chemistry AB is a laboratory-based college-preparatory course. Laboratory experiments provide the empirical basis for understanding and confirming concepts. This course emphasizes discussions, activities, and laboratory exercises, which promote the understanding of the behavior of matter at the macroscopic and the molecular-atomic levels. Chemical principles are introduced so that students will be able to explain the composition and chemical behavior of their world. Chemistry AB lays the foundation for further studies in Chemistry and also serves as an Advanced Placement Chemistry readiness course. 

*Chemistry AB meets the Grades 9-12 District physical science requirement. Students must complete one physical and one life science requirement. This course meets one year of the University of California 'd' entrance requirement for laboratory science.*

* Textbooks and Materials

* Classroom Expectations/Norms

* Classroom Proceedures

* Course Objectives

** The Periodic Table
Know how to use the periodic table to identify *metals*, *semimetals*, *nonmetals*, *halogens*, *alkali metals*, *alkaline earth metals*, *transition metals*, *lanthanide*, *actinide*, *transactinide* elements [fn:transactinite:know that the transuranium elements were synthesized and identified in laboratory experiments through the use of *nuclear accelerators*.] and trends in *ionization energy*, *electronegativity*, and the relative sizes of *ions* and *atoms*.

** Atomic Structure
Know the experimental basis for: *Thomson's discovery of the electron*, *Rutherford's nuclear atom*, *Millikan's oil drop experiment*, *Einstein and the photoelectric effect*, the development of *the quantum theory of atomic structure*, and the historical importance of the *Bohr model* of the atom

Know that *spectral lines* are the result of transitions of *electrons* between *energy levels* and that these lines correspond to photons with a *frequency* related to the energy spacing between levels by using *Planck's relationship* ($E = hv$).[fn::Know the nucleus of the atom is much smaller than the atom yet contains most of its mass.]

** Peroidicity and Electron Arrangement
Know how to relate the position of an element in the periodic table to its atomic number and atomic mass, quantum electron configuration, its reactivity with other elements in the table, and how to use the periodic table to determine the number of electrons available for bonding.

** Chemical Bonding
Know how to draw Lewis dot structures. Atoms combine to form molecules by sharing electrons to form *covalent* or *metallic* bonds or by exchanging electrons to form *ionic* bonds.[fn::Know chemical bonds between atoms in molecules such as H_2, CH_4, NH_3, H_2, CCH_2, N_2, Cl_2, and many large biological molecules are covalent.]

** The Mole Concept
Know the quantity one mole is set by defining one mole of carbon 12 atoms to have a mass of exactly 12 grams.One mole equals $6.02 \times 10^{23}$ particles (atoms or molecules). Know how to describe chemical reactions by writing balanced equations.

** Stoichiometry
Know how to determine the *molar mass* of a molecule from its *chemical formula* and a table of atomic masses and how to convert the mass of a molecular substance to moles, number of particles, or volume of gas at standard temperature and pressure.
Calculate the masses of reactants and products in a chemical reaction from the mass of one of the reactants or products and the relevant atomic masses. Calculate percent yield in a chemical reaction.Identify reactions that involve oxidation and reduction and how to balance oxidation-reduction reactions.

** Kinetic Motion of Gases
Know the random motion of molecules and their collisions with a surface create the observable pressure on that surface and explains the diffusion of gases.

Know how to convert between the Celsius and Kelvin temperature scales, there is no temperature lower than 0 Kelvin and the kinetic theory of gases relates the absolute temperature of a gas to the average kinetic energy of its molecules or atoms.

** The Gas Laws
Know how to apply the gas laws to relations between the *pressure*, *temperature*, and *volume* of any amount of an ideal gas or any mixture of ideal gases.Determine the molar mass of a molecule from its chemical formula and a table of atomic masses and how to convert the mass of a molecular substance to moles, number of particles, or volume of gas at standard temperature and pressure.

Know the values and meanings of standard temperature and pressure(STP). Solve problems by using the ideal gas law in the form $PV = nRT$.

Know how to apply *Dalton's law of partial pressures* to describe the composition of gases and *Graham's law* to predict diffusion of gases.

** Solutions
Know the definitions of *solute* and *solvent*. Describe the dissolving process at the molecular level by using the concept of random molecular motion. Calculate the concentration of a solute in terms of *grams per liter*, *molarity*, *parts per million*, and *percent composition*.

Know the relationship between the molality of a solute in a solution and the solution's depressed *freezing point* or elevated *boiling point*. Molecules in a solution are separated or purified by the methods of *chromatography* and *distillation*.

** Chemical Equilibrium
Know how to use *Le Chatelier's principle* to predict the effect of changes in concentration, temperature, and pressure. Equilibrium is established when forward and reverse reaction rates are equal.

Know temperature, pressure, and surface area affect the dissolving process. Write and calculate an equilibrium constant expression for a reaction.

** Acids and Bases
Know the observable properties of acids, bases, and salt solutions. Acids are hydrogen-ion-donating and bases are hydrogen-ion-accepting substances and the *Arrhenius*, *Brønsted-Lowry*, and *Lewis* acid-base definitions.

** Acid/Base equilibrium
Know acids are hydrogen-ion-donating and bases are hydrogen-ion-accepting substances.Strong acids and bases fully dissociate and weak acids and bases partially dissociate. Use Le Chatelier's principle to predict the effect of changes in concentration, temperature, and pressure.
- Know equilibrium is established when forward and reverse reaction rates are equal.
- Know how to write and calculate an equilibrium constant expression for a reaction.
- Know how to calculate pH from the hydrogen-ion concentration.
- Know buffers stabilize pH in acid-base reactions.

** Chemical Thermodynamics

- Know how to describe temperature and heat flow in terms of the motion of molecules (or atoms).
- Know energy is released when a material condenses or freezes and is absorbed when a material evaporates or melts.
- Know how to solve problems involving heat flow and temperature changes, using known values of specific heat and latent heat of phase change.
- Know chemical processes can either release (exothermic) or absorb (endothermic) thermal energy.
- Know how to apply Hess's law to calculate enthalpy change in a reaction.
- Know how to use the Gibbs free energy equation to determine whether a reaction would be spontaneous.
- Know the rate of reaction is the decrease in concentration of reactants or the increase in concentration of products with time.
- Know how reaction rates depend on such factors as concentration, temperature, and pressure.
- Know the definition and role of activation energy in a chemical reaction.
- Know the role a catalyst plays in increasing the reaction rate.

** Organic Chemistry

- Know the bonding characteristics of carbon that result in the formation of a large variety of structures ranging from simple hydrocarbons to complex polymers and biological molecules.
- Know the system for naming the ten simplest linear hydrocarbons and isomers that contain single bonds, simple hydrocarbons with double and triple bonds, and simple molecules that contain a benzene ring.
- Know how to identify the functional groups that form the basis of alcohols, ketones, ethers, amines, esters, aldehydes, and organic acids.
- Know large molecules (polymers), such as proteins, nucleic acids, and starch, are formed by repetitive combinations of simple subunits.
- Know amino acids are the building blocks of proteins.
- Know the R-group structure of amino acids and know how they combine to form the polypeptide backbone structure of proteins.

** Nuclear Chemistry

- Know protons and neutrons in the nucleus are held together by nuclear forces that overcome the electromagnetic repulsion between the protons.
- Know some naturally occurring isotopes of elements are radioactive, as are isotopes formed in nuclear reactions.
- Know the three most common forms of radioactive decay (alpha, beta, and gamma) and know how the nucleus changes in each type of decay.
- Know alpha, beta, and gamma radiation produce different amounts and kinds of damage in matter and have different penetrations.
- Know how to calculate the amount of a radioactive substance remaining after an integral number of half-lives have passed.

** Nuclear Energy

- Know the energy release per gram of material is much larger in nuclear fusion or fission reactions than in chemical reactions. The change in mass (calculated by $E = mc^2$ ) is small but significant in nuclear reactions.

** Particle Physics

- Know protons and neutrons have substructures and consist of particles called quarks.

* Grading Policy
